'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ParticipantCases
    
    '''<summary>
    '''hdnParticipantName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnParticipantName As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''phParticipantInfoShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phParticipantInfoShow As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lkDisplayInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lkDisplayInfo As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''ltrlAttorneyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlAttorneyName As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''lvParticipantDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lvParticipantDetails As Global.System.Web.UI.WebControls.ListView
    
    '''<summary>
    '''odsParticipantDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsParticipantDetails As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''gridCPCSCaseSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCPCSCaseSearch As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''dsSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsSearchResults As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
