'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaseDetails1
    
    '''<summary>
    '''OpenCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpenCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''OpeningDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OpeningDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CaseTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CourtNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CourtNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CourtLevelNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CourtLevelNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CourtCountyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CourtCountyNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DivisionNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivisionNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DepartmentNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DepartmentNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''UnitTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''OfficeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingCourtNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingCourtNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingCourtLevelNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingCourtLevelNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingCourtCountyNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingCourtCountyNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JudgeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JudgeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingJudgeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingJudgeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ProsecutorNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsecutorNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClosingProsecutorNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClosingProsecutorNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CaseOpenTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseOpenTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ClientCommitTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ClientCommitTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DistrictArraignmentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DistrictArraignmentDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JuryTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JuryTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JurySessionCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JurySessionCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CasePriorClientCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CasePriorClientCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''AdministrativelyClosedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AdministrativelyClosedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ArraignCustomdyReleasedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArraignCustomdyReleasedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ArraignCustomdyHeldCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArraignCustomdyHeldCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ArraignServingOtherSentenceCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ArraignServingOtherSentenceCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BailStatusCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BailStatusCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''SsaReferralCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SsaReferralCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''IncidentPoliceReportObtainedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentPoliceReportObtainedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''BailAmountLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BailAmountLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''BailConditionsLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BailConditionsLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SuperiorArraignmentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SuperiorArraignmentDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JuvenileComplaintArraignmentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JuvenileComplaintArraignmentDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''JuvenileIndictmentArraignmentDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JuvenileIndictmentArraignmentDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IncidentArrestDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentArrestDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IncidentPoliceReportDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentPoliceReportDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IncidentComplaintDateLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentComplaintDateLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IncidentTypeOfWeaponLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IncidentTypeOfWeaponLabel As Global.System.Web.UI.WebControls.Label
End Class
