'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class CaseCharges1
    
    '''<summary>
    '''OffenseLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OffenseLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''IsLeadChargeCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsLeadChargeCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''IsComittedCheckBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents IsComittedCheckBox As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''CaseChargeIDLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseChargeIDLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DocketNumberLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DocketNumberLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SentenceLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SentenceLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateOfOffenseLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfOffenseLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DateOfDispositionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DateOfDispositionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ChapterLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChapterLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SectionLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SectionLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StateChargeTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateChargeTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''StateChargeSeverityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents StateChargeSeverityLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NationalChargeTypeLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NationalChargeTypeLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NationalChargeSeverityLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NationalChargeSeverityLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ChargeStatusNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChargeStatusNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DispositionNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DispositionNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SentenceTypeNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SentenceTypeNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''CourtLevelNameLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CourtLevelNameLabel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''NoteLabel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents NoteLabel As Global.System.Web.UI.WebControls.Label
End Class
