'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ToolsMenu
    
    '''<summary>
    '''lnkAttorneysList control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkAttorneysList As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkClientLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkClientLists As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkParticipantsLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkParticipantsLists As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkProsecutorsLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkProsecutorsLists As Global.System.Web.UI.WebControls.HyperLink
    
    '''<summary>
    '''lnkJudgesLists control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkJudgesLists As Global.System.Web.UI.WebControls.HyperLink
End Class
