'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class JudgesList
    
    '''<summary>
    '''JudgeSearchBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents JudgeSearchBox As Global.Telerik.Web.UI.RadSearchBox
    
    '''<summary>
    '''gridJudges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridJudges As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''hdnJudgeID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnJudgeID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''odsJudges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsJudges As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsJudgeSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsJudgeSearch As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
