'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ProsecutorsList
    
    '''<summary>
    '''ProsecutorSearchBox control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ProsecutorSearchBox As Global.Telerik.Web.UI.RadSearchBox
    
    '''<summary>
    '''gridProsecutors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridProsecutors As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''odsProsecutors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProsecutors As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsProsecutorSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProsecutorSearch As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
