'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default6
    
    '''<summary>
    '''RadClientExportManager1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadClientExportManager1 As Global.Telerik.Web.UI.RadClientExportManager
    
    '''<summary>
    '''MetricsAjaxManager control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents MetricsAjaxManager As Global.Telerik.Web.UI.RadAjaxManager
    
    '''<summary>
    '''lblMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMsg As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSelectedDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSelectedDateRange As Global.System.Web.UI.HtmlControls.HtmlButton
    
    '''<summary>
    '''lblSelectedDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSelectedDateRange As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dteRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteRange As Global.Telerik.Web.UI.RadCalendar
    
    '''<summary>
    '''lblDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDateRange As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlDateRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDateRange As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteStartDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''dteEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteEndDate As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''rbCompareTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCompareTo As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''ddlCompareToOptions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCompareToOptions As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Panel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Panel1 As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''tabstripCharts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabstripCharts As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''multipageCharts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents multipageCharts As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''pageviewAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageviewAssignments As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''chartAreaUnitAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartAreaUnitAssignments As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''chartLineOfficeAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chartLineOfficeAssignments As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''pageviewCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageviewCases As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''ChartAreaUnitCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartAreaUnitCases As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''ChartLineOfficeCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ChartLineOfficeCases As Global.Telerik.Web.UI.RadHtmlChart
    
    '''<summary>
    '''pageviewDistribution control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents pageviewDistribution As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''tabstripGroupedMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabstripGroupedMetrics As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''multipageGroupedMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents multipageGroupedMetrics As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''UnitGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridUnitAssignmentMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitAssignmentMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''gridUnitCasesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitCasesMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''OfficeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridOfficeAssignmentMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOfficeAssignmentMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''gridOfficeCasesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOfficeCasesMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''OfficeUnitGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents OfficeUnitGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridOfficeUnitAssignmentMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOfficeUnitAssignmentMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''gridOfficeUnitsCasesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridOfficeUnitsCasesMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''UnitOfficeGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UnitOfficeGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridUnitOfficeAssignmentMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitOfficeAssignmentMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''gridUnitOfficesCasesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitOfficesCasesMetrics As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''tabstripDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents tabstripDetails As Global.Telerik.Web.UI.RadTabStrip
    
    '''<summary>
    '''multipageDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents multipageDetails As Global.Telerik.Web.UI.RadMultiPage
    
    '''<summary>
    '''AssignmentDetailsGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AssignmentDetailsGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridUnitAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitAssignments As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''CaseDetailsGroup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseDetailsGroup As Global.Telerik.Web.UI.RadPageView
    
    '''<summary>
    '''gridUnitCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridUnitCases As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''hdnStartDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnStartDate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnEndDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnEndDate As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnUnit As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnOffice As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnAttorney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnAttorney As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''dsAssignmentsByUnitsMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAssignmentsByUnitsMetrics As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsCasesByUnitsMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCasesByUnitsMetrics As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsAssignmentsByOfficesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAssignmentsByOfficesMetrics As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsCasesByOfficesMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCasesByOfficesMetrics As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsGroupedAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGroupedAssignments As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsGroupedCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsGroupedCases As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCases As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsAssignments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAssignments As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsAttorneyCases control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAttorneyCases As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsAssignmentDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAssignmentDetails As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsAttorneyAssignmentMetrics control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsAttorneyAssignmentMetrics As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''dsCaseDetails control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dsCaseDetails As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''odsCaseCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCaseCharges As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
