'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class _Default4
    
    '''<summary>
    '''AlertPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents AlertPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''lblAlertPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAlertPanel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''SearchPanel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SearchPanel As Global.System.Web.UI.WebControls.Panel
    
    '''<summary>
    '''RadAjaxPanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadAjaxPanel1 As Global.Telerik.Web.UI.RadAjaxPanel
    
    '''<summary>
    '''lblClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClient As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtClientName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClientName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblCaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseNumber As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCaseNumber As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCharge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCharge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCharge As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblCaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlCaseType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlCaseType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblOpenedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOpenedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlOpenedFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOpenedFromDate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteCaseOpenedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteCaseOpenedFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''phCaseOpenedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCaseOpenedTo As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblCaseOpenedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCaseOpenedTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dteCaseOpenedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteCaseOpenedTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lblClosedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosedFrom As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlClosedFromDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlClosedFromDate As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''dteCaseClosedFrom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteCaseClosedFrom As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''phCaseClosedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCaseClosedTo As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''lblClosedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblClosedTo As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''dteCaseClosedTo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dteCaseClosedTo As Global.Telerik.Web.UI.RadDatePicker
    
    '''<summary>
    '''lblDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblDivision As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlDivision control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlDivision As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblOffice As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlOffice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlOffice As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblParticipant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblParticipant As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtParticipantName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtParticipantName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblAttorney control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblAttorney As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtAttorneyName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAttorneyName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblProsecutor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProsecutor As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtProsecutorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProsecutorName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblJudge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblJudge As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtJudgeName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtJudgeName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblSSA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSSA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtSSAName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSSAName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''lblInvestigator control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblInvestigator As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtInvestigatorName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvestigatorName As Global.Telerik.Web.UI.RadAutoCompleteBox
    
    '''<summary>
    '''chkHeldInCustody control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkHeldInCustody As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkCaseIsOpen control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCaseIsOpen As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''chkSSAReferral control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSSAReferral As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''gridCPCSCaseSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gridCPCSCaseSearch As Global.Telerik.Web.UI.RadGrid
    
    '''<summary>
    '''SqlDSSearchResultsXX control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSSearchResultsXX As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''SqlDSSearchResults control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents SqlDSSearchResults As Global.System.Web.UI.WebControls.SqlDataSource
    
    '''<summary>
    '''odsClients control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsClients As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsAttorneys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsAttorneys As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsProsecutors control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsProsecutors As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsJudges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsJudges As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsParticipants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsParticipants As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsInvestigators control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsInvestigators As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsSSAs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsSSAs As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsOffices control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsOffices As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsDivisions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsDivisions As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsUnits As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsCaseTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCaseTypes As Global.System.Web.UI.WebControls.ObjectDataSource
    
    '''<summary>
    '''odsCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents odsCharges As Global.System.Web.UI.WebControls.ObjectDataSource
End Class
