'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ManagementCaseDetails
    
    '''<summary>
    '''hdnCaseGUID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCaseGUID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''hdnCaseID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hdnCaseID As Global.System.Web.UI.WebControls.HiddenField
    
    '''<summary>
    '''phNoCaseFound control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phNoCaseFound As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''phCaseIsValid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents phCaseIsValid As Global.System.Web.UI.WebControls.PlaceHolder
    
    '''<summary>
    '''ltrlCaseNumber control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ltrlCaseNumber As Global.System.Web.UI.WebControls.Literal
    
    '''<summary>
    '''CaseInformation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseInformation As Global.Defender.CaseInformation
    
    '''<summary>
    '''CaseClient control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseClient As Global.Defender.CaseClient
    
    '''<summary>
    '''CaseAttorneys control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseAttorneys As Global.Defender.CaseAttorneys
    
    '''<summary>
    '''CaseCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseCharges As Global.Defender.CaseCharges
    
    '''<summary>
    '''CaseParticipants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseParticipants As Global.Defender.CaseParticipants
    
    '''<summary>
    '''CaseSchedule control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CaseSchedule As Global.Defender.CaseSchedule
End Class
